ContactsControl/Models/RedefinePassword/RedefinePasswordModel.cs
using System.ComponentModel.DataAnnotations;

namespace ContactsControl.Models
{
    public class RedefinePasswordModel
    {
        public long UserId { get; set; }
        [Required(ErrorMessage = "Informe a senha atual")]
        public string CurrentPassword { get; set; }
        [Required(ErrorMessage = "Informe a nova senha")]
        public string NewPassword { get; set; }
        [Required(ErrorMessage = "Confirme a nova senha")]
        [Compare("NewPassword", ErrorMessage = "Senha incorreta")]
        public string ConfirmNewPassword { get; set; }
    }
}

ContactsControl/Controllers/RedefinePassword/RedefinePasswordController.cs
using ContactsControl.Models;
using ContactsControl.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ContactsControl.Controllers
{
    public class RedefinePasswordController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly Helpers.ISession _session;

        public RedefinePasswordController(IUserRepository userRepository, Helpers.ISession session)
        {
            _userRepository = userRepository;
            _session = session;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Update(RedefinePasswordModel redefinePasswordModel)
        {
            try
            {
                UserModel userModel = _session.GetUserSession();
                redefinePasswordModel.UserId = userModel.Id;

                if (ModelState.IsValid)
                {
                    _userRepository.RedefinePassword(redefinePasswordModel);
                    TempData["SuccessMessage"] = "Senha alterada com sucesso";
                    return View("Index", redefinePasswordModel);
                }

                return View("Index", redefinePasswordModel);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Erro: {ex.Message}";
                return View("Index", redefinePasswordModel);
            }
        }
    }
}

ContactsControl/Views/RedefinePassword/Index.cshtml
<!DOCTYPE html>
<html>
    <head>
        @using ContactsControl.Enums;
        @model RedefinePasswordModel
        @{
            ViewData["Title"] = "Redefinir senha do usuário";
        }
    </head>
    <body>
        <div class="text-center">
            <h1 class="display-4">Redefinir senha do usuário</h1>
        </div>

        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-success" role="alert">
                <button type="button" class="btn btn-success btn-sm close-alert" arial-label="Close">X</button>
                @TempData["SuccessMessage"]
            </div>
        }

        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger" role="alert">
                <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
                @TempData["ErrorMessage"]
            </div>
        }

        <form asp-controller="RedefinePassword" asp-action="Update" method="post">

            <div class="form-group mb-3">
                <label for="currentPassword">Senha atual</label> @Html.ValidationMessageFor(x => x.CurrentPassword)
                <input type="password" asp-for="CurrentPassword" class="form-control" placeholder="Informe a senha atual">
            </div>

            <div class="form-group mb-3">
                <label for="newPassword">Nova senha</label> @Html.ValidationMessageFor(x => x.NewPassword)
                <input type="password" asp-for="NewPassword" class="form-control" placeholder="Informe a nova senha">
            </div>

            <div class="form-group mb-3">
                <label for="confirmNewPassword">Confirmar nova senha</label> @Html.ValidationMessageFor(x => x.ConfirmNewPassword)
                <input type="password" asp-for="ConfirmNewPassword" class="form-control" placeholder="Confirme   a nova senha">
            </div>

            <button type="submit" class="btn btn-primary d-block w-100 mb-3">Alterar</button>
            <a class="btn btn-danger d-block w-100 mb-3" role="button" asp-controller="Home" asp-action="Index">Cancelar</a>
        </form>
    </body>
</html>